---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: python manage.py test

      - name: Lint
        run: flake8